apiVersion: v1
kind: Service
metadata:
  name: product-webapp
  labels:
    app: project
    service: product-webapp
spec:
  clusterIP: none
  
  ports:
  - port: 4200
    name: http
  selector:
    app: project

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-webapp
  labels:
    app: project
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
      version: v1
  template:
    metadata:
      labels:
        app: project
        version: v1
    spec:
      containers:
       - name: product
        image: param036/product-webapp:latest
        name: product
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4200
